package com.codigo.smartstore.timeline.period;

public enum PeriodRelation {
	AFTER,
	STARTTOUCHING,
	STARTINSIDE,
	INSIDESTARTTOUCHING,
	ENCLOSINGSTARTTOUCHING,
	ENCLOSING,
	ENCLOSINGENDTOUCHING,
	EXACTMATCH,
	INSIDE,
	INSIDEENDTOUCHING,
	ENDINSIDE,
	ENDTOUCHING,
	BEFORE

}
