#https://javadeveloper.pl/yaml/
api:
   endpoint:
      accounting: /api/v1
logging:
   level: error
   level.org.hibernate.SQL: debug
   level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
management:
   endpoint:
      shutdown:
         enabled: true
   endpoints:
      web:
         exposure:
            include: '*'
server:
   port: 8081
   servlet:
      contextPath: /smartstore
spring:
   data:
      web:
         pageable:
            default-page-size: 10
            max-page-size: 2000
            one-indexed-parameters: false
            page-parameter: page
            prefix: ''
            qualifier-delimiter: _
            size-parameter: size
   datasource:
      dev:
         driver-class-name: org.h2.Driver
         password: ''
         pool-size: 30
         url: jdbc:h2:mem:mydb
         username: sa
      prod:
         driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
         password: ''
         pool-size: 30
         url: jdbc:sqlserver://HWD19Y2\MSSQL;port=64182;databaseName=smartstore
         username: ''
   jpa:
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      generate-ddl: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
      show-sql: true
   mail:
      host: smtp.gmail.com
      password: <login password to smtp server>
      port: 587
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
      username: <login user to smtp server>
   main:
      banner-mode: off
complex:
   name: defaultName
   user: defaultUser
   password: defaultPassword
   inputs:
   -  user: user
      password: secret
   -  user: otheruser
      password: secret2
   outputs:
   -  user: someuser
      password: asecret
   -  user: someotheruser
      password: anothersecret