/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package com.codigo.smartstore.xbase.gui.explorer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrzej.radziszewski
 */
public class frmDasboard
		extends
		javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 6150689192956430268L;

	/**
	 * Creates new form NewJFrame
	 */
	public frmDasboard() {

		this.initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.pnlMain = new javax.swing.JPanel();
		this.pnlMain.setBorder(null);
		this.pnlLeft = new javax.swing.JPanel();
		this.pnlLeft.setAlignmentX(2.5f);
		this.pnlLeft.setBorder(new MatteBorder(
				0, 0, 0, 0, new Color(
						192, 192, 192)));
		this.pnlOption = new javax.swing.JPanel();
		this.barOption = new javax.swing.JToolBar();
		this.barOption.setBackground(new Color(
				240, 240, 240));
		this.jButton5 = new javax.swing.JButton();
		this.jButton6 = new javax.swing.JButton();
		this.jButton7 = new javax.swing.JButton();
		this.jButton8 = new javax.swing.JButton();
		this.jButton9 = new javax.swing.JButton();
		this.jButton10 = new javax.swing.JButton();
		this.jPanel1 = new javax.swing.JPanel();
		this.jPanel1.setBorder(new MatteBorder(
				0, 0, 0, 0, new Color(
						192, 192, 192)));
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.jScrollPane1.setAutoscrolls(true);
		this.jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		this.jScrollPane1.setRequestFocusEnabled(false);
		this.jScrollPane1.setFocusTraversalKeysEnabled(false);
		this.jScrollPane1.setFocusable(false);
		this.jTable1 = new javax.swing.JTable();
		this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
		this.jTable1.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
		this.jTable1.setFillsViewportHeight(true);
		this.jTable1.setRequestFocusEnabled(false);
		this.jTable1.setDoubleBuffered(true);
		this.jTable1.setDragEnabled(true);
		this.jTable1.setFocusTraversalKeysEnabled(false);
		this.jTable1.setFocusable(false);
		this.jTable1.setBorder(new EmptyBorder(
				0, 0, 0, 0));
		this.mnuMain = new javax.swing.JMenuBar();
		this.jMenu8 = new javax.swing.JMenu();
		this.jMenuItem2 = new javax.swing.JMenuItem();
		this.jMenuItem3 = new javax.swing.JMenuItem();
		this.jSeparator1 = new javax.swing.JPopupMenu.Separator();
		this.jMenuItem1 = new javax.swing.JMenuItem();
		this.jMenu1 = new javax.swing.JMenu();
		this.jMenu4 = new javax.swing.JMenu();
		this.jMenu11 = new javax.swing.JMenu();
		this.jMenu2 = new javax.swing.JMenu();
		this.jMenu7 = new javax.swing.JMenu();
		this.jMenu9 = new javax.swing.JMenu();
		this.jMenu10 = new javax.swing.JMenu();
		this.jMenu5 = new javax.swing.JMenu();
		this.jMenu6 = new javax.swing.JMenu();
		this.jMenu3 = new javax.swing.JMenu();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.setTitle("XBase Workspace ver. 2017.1");
		this.setMinimumSize(new java.awt.Dimension(
				800, 600));

		this.pnlMain.setBackground(Color.LIGHT_GRAY);
		this.pnlMain.setName("pnlMain"); // NOI18N
		final BorderLayout bl_pnlMain = new BorderLayout();
		bl_pnlMain.setHgap(1);
		bl_pnlMain.setVgap(1);
		this.pnlMain.setLayout(bl_pnlMain);

		this.pnlLeft.setBackground(new Color(
				255, 255, 255));
		this.pnlLeft.setPreferredSize(new Dimension(
				250, 711));
		// renderer.setTextSelectionColor(Color.white);
		// renderer.setBackgroundSelectionColor(Color.blue);
		// renderer.setBorderSelectionColor(Color.gray);
		// renderer.setBackground(new Color(0, 43, 54));
		// renderer.setBackgroundNonSelectionColor(new Color(0, 43, 54));
		// renderer.setBackgroundNonSelectionColor(new Color(240, 240, 240));

		this.pnlMain.add(this.pnlLeft, BorderLayout.WEST);
		this.pnlLeft.setLayout(new BorderLayout(
				0, 0));

		this.pnlOption.setCursor(new java.awt.Cursor(
				java.awt.Cursor.DEFAULT_CURSOR));
		this.pnlOption.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
		this.pnlOption.setFocusable(false);
		this.pnlOption.setFont(new java.awt.Font(
				"Segoe UI", 0, 12)); // NOI18N
		this.pnlOption.setPreferredSize(new java.awt.Dimension(
				770, 67));
		this.pnlOption.setRequestFocusEnabled(false);
		this.pnlOption.setVerifyInputWhenFocusTarget(false);
		this.pnlOption.setLayout(new java.awt.BorderLayout());

		this.barOption.setBorder(new MatteBorder(
				0, 0, 0, 0, new Color(
						192, 192, 192)));
		this.barOption.setFloatable(false);
		this.barOption.setAutoscrolls(true);
		this.barOption.setDoubleBuffered(true);
		this.barOption.setFocusCycleRoot(true);
		this.barOption.setMaximumSize(new java.awt.Dimension(
				237, 62));
		this.barOption.setMinimumSize(new java.awt.Dimension(
				237, 62));
		this.barOption.setPreferredSize(new java.awt.Dimension(
				107, 62));
		this.barOption.setRequestFocusEnabled(false);
		this.barOption.setVerifyInputWhenFocusTarget(false);

		this.jButton5.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton5.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-menu.png"))); // NOI18N
		this.jButton5.setText("Operacje");
		this.jButton5.setAlignmentX(0.5F);
		this.jButton5.setAutoscrolls(true);
		this.jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton5.setFocusable(false);
		this.jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton5.setRequestFocusEnabled(false);
		this.jButton5.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton5);

		this.jButton6.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton6.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-insert-row-above(1).png"))); // NOI18N
		this.jButton6.setText("Nowy rekord");
		this.jButton6.setAlignmentX(0.5F);
		this.jButton6.setAutoscrolls(true);
		this.jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton6.setFocusable(false);
		this.jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton6.setRequestFocusEnabled(false);
		this.jButton6.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton6);

		this.jButton7.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton7.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-grid.png"))); // NOI18N
		this.jButton7.setText("Struktura");
		this.jButton7.setAlignmentX(0.5F);
		this.jButton7.setAutoscrolls(true);
		this.jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton7.setFocusable(false);
		this.jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton7.setRequestFocusEnabled(false);
		this.jButton7.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton7);

		this.jButton8.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton8.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-monitor.png"))); // NOI18N
		this.jButton8.setText("Monitoring");
		this.jButton8.setAlignmentX(0.5F);
		this.jButton8.setAutoscrolls(true);
		this.jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton8.setFocusable(false);
		this.jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton8.setRequestFocusEnabled(false);
		this.jButton8.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton8);

		this.jButton9.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton9.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-support.png"))); // NOI18N
		this.jButton9.setText("Preferencje");
		this.jButton9.setAlignmentX(0.5F);
		this.jButton9.setAutoscrolls(true);
		this.jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton9.setFocusable(false);
		this.jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton9.setRequestFocusEnabled(false);
		this.jButton9.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton9);

		this.jButton10.setFont(new java.awt.Font(
				"Segoe UI", 1, 12)); // NOI18N
		this.jButton10.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-synchronize.png"))); // NOI18N
		this.jButton10.setText("Synchronizacja");
		this.jButton10.setAlignmentX(0.5F);
		this.jButton10.setAutoscrolls(true);
		this.jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
		this.jButton10.setFocusable(false);
		this.jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		this.jButton10.setRequestFocusEnabled(false);
		this.jButton10.setSelectedIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-merge-cells.png"))); // NOI18N
		this.jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		this.barOption.add(this.jButton10);

		this.pnlOption.add(this.barOption, java.awt.BorderLayout.CENTER);

		this.btnNewButton = new JButton(
				"Administracja");
		this.btnNewButton.setBackground(new Color(
				240, 240, 240));
		this.btnNewButton.setMinimumSize(new Dimension(
				93, 23));
		this.btnNewButton.setPreferredSize(new Dimension(
				93, 23));
		this.btnNewButton.setFocusable(false);
		this.btnNewButton.setRolloverEnabled(false);
		this.btnNewButton.setRequestFocusEnabled(false);
		this.btnNewButton.setIcon(new javax.swing.ImageIcon(
				this.getClass()
						.getResource("/icons8-check-file.png")));
		this.btnNewButton.setHorizontalTextPosition(SwingConstants.CENTER);
		this.btnNewButton.setFont(new Font(
				"Segoe UI", Font.BOLD, 12));
		this.btnNewButton.setBorder(new EmptyBorder(
				10, 10, 10, 10));
		this.btnNewButton.setVerticalTextPosition(SwingConstants.BOTTOM);
		this.barOption.add(this.btnNewButton);

		this.pnlMain.add(this.pnlOption, java.awt.BorderLayout.NORTH);

		this.jPanel1.setBackground(new java.awt.Color(
				204, 204, 255));
		this.jPanel1.setPreferredSize(new Dimension(
				250, 682));

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				this.jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGap(0, 249, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGap(0, 711, Short.MAX_VALUE));
		this.jPanel1.setLayout(jPanel1Layout);

		this.pnlMain.add(this.jPanel1, java.awt.BorderLayout.EAST);

		this.jScrollPane1.setBorder(new EmptyBorder(
				0, 2, 0, 2));

		this.jTable1.setFont(new java.awt.Font(
				"Segoe UI", 0, 12)); // NOI18N
		this.jTable1.setModel(new DefaultTableModel(
				new Object[][] {
					{ null, null, null, null, null, null, null, null, null, null },
					{ null, null, null, null, null, null, null, null, null, null },
					{ null, null, null, null, null, null, null, null, null, null },
					{ null, null, null, null, null, null, null, null, null, null }, },
				new String[] {
					"New column", "New column", "New column", "Title 1", "Title 2", "Title 3", "Title 4", "New column",
					"New column", "New column" }));
		this.jTable1.getColumnModel()
				.getColumn(3)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(3)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(4)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(4)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(5)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(5)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(6)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(6)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(7)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(7)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(8)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(8)
				.setMinWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(9)
				.setPreferredWidth(100);
		this.jTable1.getColumnModel()
				.getColumn(9)
				.setMinWidth(100);
		this.jTable1.setGridColor(new java.awt.Color(
				204, 204, 204));
		this.jTable1.setRowHeight(25);

		this.jTable1.addKeyListener(new KeyAdapter() {

			@Override
			public void keyPressed(final KeyEvent e) {

				if (e.getKeyCode() == KeyEvent.VK_ENTER) {

					final int row = frmDasboard.this.jTable1.getSelectedRow();
					final int column = frmDasboard.this.jTable1.getSelectedColumn();

					// resul is the new value to insert in the DB
					final String resul = frmDasboard.this.jTable1.getValueAt(row, column)
							.toString();
					// id is the primary key of my DB
					final String id = frmDasboard.this.jTable1.getValueAt(row, 0)
							.toString();

					// update is my method to update. Update needs the id for
					// the where clausule. resul is the value that will receive
					// the cell and you need column to tell what to update.
					System.out.println(id + resul
							+ column);
				}
			}
		});

		this.jScrollPane1.setViewportView(this.jTable1);

		this.pnlMain.add(this.jScrollPane1, java.awt.BorderLayout.CENTER);

		this.getContentPane()
				.add(this.pnlMain, java.awt.BorderLayout.CENTER);

		this.mnuMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));

		this.jMenu8.setText("Application");

		this.jMenuItem2.setAccelerator(
			javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
		this.jMenuItem2.setText("Settings");
		this.jMenu8.add(this.jMenuItem2);

		this.jMenuItem3.setText("jMenuItem3");
		this.jMenu8.add(this.jMenuItem3);
		this.jMenu8.add(this.jSeparator1);

		this.jMenuItem1.setAccelerator(
			javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
		this.jMenuItem1.setText("Exit");
		this.jMenuItem1.addActionListener(frmDasboard.this::jMenuItem1ActionPerformed);
		this.jMenu8.add(this.jMenuItem1);

		this.mnuMain.add(this.jMenu8);

		this.jMenu1.setText("Database");
		this.mnuMain.add(this.jMenu1);

		this.jMenu4.setText("Table");
		this.mnuMain.add(this.jMenu4);

		this.jMenu11.setText("Index");
		this.mnuMain.add(this.jMenu11);

		this.jMenu2.setText("Record");
		this.mnuMain.add(this.jMenu2);

		this.jMenu7.setText("Search");
		this.mnuMain.add(this.jMenu7);

		this.jMenu9.setText("Tasks");
		this.mnuMain.add(this.jMenu9);

		this.jMenu10.setText("Scheduler");
		this.mnuMain.add(this.jMenu10);

		this.jMenu5.setText("Tools");
		this.mnuMain.add(this.jMenu5);

		this.jMenu6.setText("Window");
		this.mnuMain.add(this.jMenu6);

		this.jMenu3.setText("Help");
		this.mnuMain.add(this.jMenu3);

		this.setJMenuBar(this.mnuMain);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed

		this.jTable1.setAutoCreateRowSorter(true);
		this.jTable1.setFillsViewportHeight(true);
		this.jTable1.setComponentPopupMenu(new TablePopupMenu());
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args[]) {

		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {

			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
				if ("Windows".equals(info.getName())) {

					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {

			java.util.logging.Logger.getLogger(frmDasboard.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater((
		) -> {

			final JFrame form = new frmDasboard();
			form.setLocationRelativeTo(null);
			form.setVisible(true);
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JToolBar barOption;

	private javax.swing.JButton jButton10;

	private javax.swing.JButton jButton5;

	private javax.swing.JButton jButton6;

	private javax.swing.JButton jButton7;

	private javax.swing.JButton jButton8;

	private javax.swing.JButton jButton9;

	private javax.swing.JMenu jMenu1;

	private javax.swing.JMenu jMenu10;

	private javax.swing.JMenu jMenu11;

	private javax.swing.JMenu jMenu2;

	private javax.swing.JMenu jMenu3;

	private javax.swing.JMenu jMenu4;

	private javax.swing.JMenu jMenu5;

	private javax.swing.JMenu jMenu6;

	private javax.swing.JMenu jMenu7;

	private javax.swing.JMenu jMenu8;

	private javax.swing.JMenu jMenu9;

	private javax.swing.JMenuItem jMenuItem1;

	private javax.swing.JMenuItem jMenuItem2;

	private javax.swing.JMenuItem jMenuItem3;

	private javax.swing.JPanel jPanel1;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JPopupMenu.Separator jSeparator1;

	private javax.swing.JTable jTable1;

	private javax.swing.JMenuBar mnuMain;

	private javax.swing.JPanel pnlLeft;

	private javax.swing.JPanel pnlMain;

	private javax.swing.JPanel pnlOption;

	private JButton btnNewButton;

}

class TablePopupMenu
		extends
		JPopupMenu {

	/**
	 *
	 */
	private static final long serialVersionUID = 4178042546396081744L;
	private final JMenuItem delete;

	protected TablePopupMenu() {

		super();
		this.add("Dodaj rekord...")
				.addActionListener(e -> {

					final JTable table = (JTable) this.getInvoker();
					final DefaultTableModel model = (DefaultTableModel) table.getModel();
					model.addRow(new Object[] { "1", "2", "3", "4" });
					model.addRow(new Object[] { "3 dasd1", "ąśął", "q wq  w   qw  qw", "123123" });
					model.addRow(new Object[] { "1", "2", "3", "4" });
					model.addRow(new Object[] { "3 dasd1", "ąśął", "q wq  w   qw  qw", "123123" });
					model.addRow(new Object[] { "1", "2", "3", "4" });
					model.addRow(new Object[] { "3 dasd1", "ąśął", "q wq  w   qw  qw", "123123" });
					model.addRow(new Object[] { "1", "2", "3", "4" });
					model.addRow(new Object[] { "1", "2", "3", "4" });
					model.addRow(new Object[] { "3 dasd1", "ąśął", "q wq  w   qw  qw", "123123" });
					model.addRow(new Object[] { "3 dasd1", "ąśął", "q wq  w   qw  qw", "123123" });
					final Rectangle r = table.getCellRect(model.getRowCount() - 1, 0, true);
					table.scrollRectToVisible(r);
				});
		this.addSeparator();
		this.delete = this.add("Usuń rekord(y)...");
		this.delete.addActionListener(e -> {

			final JTable table = (JTable) this.getInvoker();
			final DefaultTableModel model = (DefaultTableModel) table.getModel();
			final int[] selection = table.getSelectedRows();
			for (int i = selection.length - 1; i >= 0; i--)
				model.removeRow(table.convertRowIndexToModel(selection[i]));
		});
	}

	@Override
	public void show(final Component c, final int x, final int y) {

		if (c instanceof JTable) {

			this.delete.setEnabled(((JTable) c).getSelectedRowCount() > 0);
			super.show(c, x, y);
		}
	}

}
