/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package com.codigo.smartstore.xbase.gui.explorer;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author andrzej.radziszewski
 */
public class MainForm
		extends
		javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 4579435363387585085L;

	/**
	 * Creates new form MainForm
	 */
	public MainForm() {

		this.initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jPanel2 = new javax.swing.JPanel();
		this.filler2 = new javax.swing.Box.Filler(
				new java.awt.Dimension(
						0, 0),
				new java.awt.Dimension(
						0, 0),
				new java.awt.Dimension(
						0, 32767));
		this.filler1 = new javax.swing.Box.Filler(
				new java.awt.Dimension(
						0, 0),
				new java.awt.Dimension(
						100, 100),
				new java.awt.Dimension(
						32767, 32767));
		this.jPanel1 = new javax.swing.JPanel();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.setPreferredSize(new java.awt.Dimension(
				800, 600));
		this.getContentPane()
				.setLayout(new javax.swing.BoxLayout(
						this.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

		this.jPanel2.setBackground(new java.awt.Color(
				255, 204, 153));

		final javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				this.jPanel2);
		this.jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(this.filler2,
							javax.swing.GroupLayout.PREFERRED_SIZE,
							javax.swing.GroupLayout.DEFAULT_SIZE,
							javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(915, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
					jPanel2Layout.createSequentialGroup()
							.addContainerGap(144, Short.MAX_VALUE)
							.addComponent(this.filler2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addGap(30, 30, 30)));

		this.getContentPane()
				.add(this.jPanel2);
		this.getContentPane()
				.add(this.filler1);

		this.jPanel1.setBackground(new java.awt.Color(
				204, 255, 204));

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 925, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 209, Short.MAX_VALUE));

		this.getContentPane()
				.add(this.jPanel1);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args[]) {

		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {

			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
				if ("Nimbus".equals(info.getName())) {

					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
		} catch (final ClassNotFoundException ex) {

			java.util.logging.Logger.getLogger(MainForm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final InstantiationException ex) {

			java.util.logging.Logger.getLogger(MainForm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final IllegalAccessException ex) {

			java.util.logging.Logger.getLogger(MainForm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final javax.swing.UnsupportedLookAndFeelException ex) {

			java.util.logging.Logger.getLogger(MainForm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater((
		) -> new MainForm().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.Box.Filler filler1;
	private javax.swing.Box.Filler filler2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;

	// End of variables declaration//GEN-END:variables
	public static void runGui() {

		final JPanel panel = new JPanel();
		final Dimension expectedDimension = new Dimension(
				500, 300);

		panel.setPreferredSize(expectedDimension);
		panel.setMaximumSize(expectedDimension);
		panel.setMinimumSize(expectedDimension);

		panel.setBackground(Color.RED); // for debug only

		final Box box = new Box(
				BoxLayout.Y_AXIS);

		box.add(Box.createVerticalGlue());
		box.add(panel);
		box.add(Box.createVerticalGlue());

		final JFrame frame = new JFrame();
		frame.add(box);
		frame.setMaximumSize(new Dimension(
				800, 600));
		frame.setMinimumSize(new Dimension(
				800, 600));
		frame.setSize(new Dimension(
				800, 600));
		frame.setLocationRelativeTo(null);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		// frame.setMinimumSize(frame.getMinimumSize()); // cannot be resized-
		frame.setVisible(true);

	}

}
